execute _runtime#init()

" Key map here for all third party app 's plugin to use

" jk is escape
inoremap jk <esc>

" This one is pretty cool. It visually selects the block of characters you
" added last time you were in INSERT mode.
nnoremap gV `[v`]

nnoremap <leader><space> :nohlsearch<CR> " \<space>

map <F2> :retab <CR> :w <CR>

" move to beginning/end of line
nnoremap B ^
nnoremap E $

