" Key map here for all third party app 's plugin to use

" jk is escape
inoremap jk <esc>

nnoremap <leader><space> :nohlsearch<CR> " \<space>

map <F2> :retab <CR> :w <CR>

" move to beginning/end of line
nnoremap B ^
nnoremap E $

" `gf` opens file under cursor in a new vertical split
nnoremap gf :vertical wincmd f<CR>

let g:filepath_sep = has('win32') ? '\' : '/'
let g:dot_vim_dir = $HOME
if has('unix')
  let g:dot_vim_dir = $HOME.g:filepath_sep.'.vim'
elseif (has('win32') || has('win64')) && !has('win32unix')
  let g:dot_vim_dir = $HOME.g:filepath_sep.'vimfiles'
end

" Load plugins
if filereadable(g:dot_vim_dir.g:filepath_sep . 'autoload/init_runtime.vim')
  execute init_runtime#Init()
endif

