" Key map here for all third party app 's plugin to use

" jk is escape
if v:version >= 500
  inoremap jk <esc>
endif

nnoremap <leader><space> :nohlsearch<CR>

map <F2> :retab <CR> :w <CR>

" `gf` opens file under cursor in a new vertical split
nnoremap gf :vertical wincmd f<CR>

if has('unix')
  let g:dot_vim_dir = $HOME.'/.vim'
elseif (has('win32') || has('win64')) && !has('win32unix')
  let g:dot_vim_dir = $HOME.'/vimfiles'
end

" Load plugins
if filereadable(g:dot_vim_dir . '/autoload/init_runtime.vim')
  execute init_runtime#Init()
endif

" Settings
" --- Code Style ---
" set softtabstop = 0
set expandtab
set tabstop=4
set smartindent
set autoindent
set shiftwidth=2
set softtabstop=4

" FOLD -- cLOSE/oPen on file
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent

set nocompatible
set backspace=2
set number
set incsearch        " Search on typing
set hlsearch         " Highlight search
set showcmd
set cindent
set nowb
set swapfile
set cursorline
set autoread
set autowrite
set laststatus=2 " Always show airline
set ttimeoutlen=50
set wildmenu
set nolazyredraw
set showmatch
set ttyfast
set noeb vb t_vb=
set nolist

if has('multi_byte')
  set fileencodings=iso-2022-jp,euc-jp,sjis,utf-8
end

