<?php
$f = "sdfsd f";
$f = [
"" => 'test',
];
$f = 1;
?>
<?= 1 ?>
<?php // end ?>
<?php
/**
*
*
*
*/
for ($i = 0; $i < 10; $i++)
{
for ($i = 0; $i < 10; $i++)
{
for ($i = 0; $i < 10; $i++)
{
}
}
}
?>
<?php if (true) : ?>
<?php endif ?>

<?php foreach ($a as $b) : ?>
<?php endforeach ?>

<?php for ($i = 0; $i < 10; $i++) : ?>
<div class="test">
  hehehe
</div>
<?php endfor ?>
<div class="test2">
  <span>
    <?php for ($i = 0; $i < 10; $i++) { ?>
    <span>
      sfsdfsdf
    </span>
    <?php } ?>
  </span>
</div>
<script></script>
<script></script>

